### ISSUE TITLE
[ENHANCEMENT STYLING]: Fixing the hero section behaviour

### ISSUE THREAD

**Issue by itsmohit097** [itsmohit097/medi-hub#62]
## Description

Hero Section is taking the extra width on the right side

## Actual Behavior
-- Taking the extra width 
-- slider auto-play speed is too fast now
-- slider is working on scroll

## Expected Behavior
-- Width will be set to the screen size (full width) 
-- slider auto-play speed will be slow
-- slider will continue working as the page loads (infinitely), not on the scroll

## Screenshots (if applicable)
Actual:
![Screenshot 2024-05-12 101415](https://github.com/itsmohit097/medi-hub/assets/125040386/5ebd69c9-dfad-45a8-9e77-30981a6dbe60)

**Comment by MitulSonagara** [comment]
@itsmohit097 I can do this very well. Can you please assign this to me.

**Comment by Harshitazz** [comment]
assign it to me .

**Comment by neharika2004** [comment]
Hey, i understood your issue and i believe i can solve it as i have a good experience about responsive devices if possible please assign this to me.

**Comment by amantaphelix** [comment]
Hello,

I would like to resolve this issue. I have reviewed the current behavior, identified the expected behavior, and prepared a solution. I believe I can address the following issues:
1.Hero Section taking extra width on the right side.
2.Slider auto-play speed being too fast.
3.Slider working on scroll, instead of continuing to work as the page loads.
Please assign this issue to me.

**Comment by Harshillagg** [comment]
Hi! I can resolve this issue very easily ... pls assign this to me ... i can also make it responsive for every screen size very easily ... i have done this kind of work before and i believe i can resolve this issue
